config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root "home#index"

  resources :homeworks, only: [:index, :new, :create, :edit, :update, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :teacher, class_name: "User", foreign_key: "teacher_id"
  validates :title, presence: true
  validates :description, presence: true
  validates :deadline,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :homeworks, foreign_key: :teacher_id, dependent: :destroy

         enum role: { student: 0, teacher: 1 }


         after_initialize :set_default_role, if: :new_record?

         private
       
         def set_default_role
           self.role ||= :student 
         end
        end       

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! 
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end

  def after_sign_in_path_for(resource)
    if resource.role == "teacher"
      homeworks_path 
    else
      root_path 
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_teacher, only: [:new, :create]

  def index
    @homeworks = Homework.all
  end

  def new
    @homework = Homework.new
  end

  def create
    @homework = Homework.new(homework_params)
    @homework.teacher_id = current_user.id
  
    if @homework.save
      respond_to do |format|
        format.html { redirect_to homeworks_path, notice: "宿題を登録しました" }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("homework_form", partial: "homeworks/form", locals: { homework: @homework }) }
      end
    end
  end

  def show
  end


  private

  def homework_params
    params.require(:homework).permit(:title, :description, :deadline, :teacher_id)
  end

  def authorize_teacher
    unless current_user.teacher?
      redirect_to root_path, alert: "先生のみが宿題を投稿できます。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ホームページ</title>
  <style>
    body {
      background-color: #007bff; /* 青色 */
      color: white;
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 50px;
    }
    h1 {
      font-size: 3em;
    }
    p {
      font-size: 1.5em;
    }
  </style>
</head>
<body>
  <h1>ようこそ！</h1>
  <p>これは青色のホームページです。</p>
  <% if user_signed_in? %>
     <%= form_tag(destroy_user_session_path, method: :delete) do %>
    <%= submit_tag 'Logout', class: "logout-link" %>
  <% end %>
<% else %>
  <%= link_to 'Login', new_user_session_path, class: "logout-link" %>
  <%= link_to 'Sign up', new_user_registration_path, class: "logout-link" %>
  <% end %>

</body>
</html>

app/views/homeworks/index.html.erb
<h2>宿題一覧</h2>

<% @homeworks.each do |homework| %>
  <div>
    <h3><%= homework.title %></h3>
    <p><%= homework.description %></p>
    <p>締切日: <%= homework.deadline.strftime("%Y-%m-%d") %></p>
    <p>登録者: <%= homework.teacher.email %></p>
  </div>
<% end %>

<% if current_user.teacher? %>
  <%= link_to "新しい宿題を登録", new_homework_path %>
<% end %>

app/views/homeworks/new.html.erb
<h2>宿題を登録</h2>

<%= form_with(model: homework, local: false, id: "homework_form") do |f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description, "詳細" %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :deadline, "締切日" %><br>
    <%= f.date_field :deadline %>
  </div>

  <div>
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeworkApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
  <!-- ログインしている場合はログアウトリンクを表示 -->
</header>
    <%= yield %>
  </body>
</html>